version: '3.8'

services:
  app:
    image: sirajulmuneer414/lenscraft:latest
    container_name: lenscraft-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lenscraft
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - ADMIN_CODE=${ADMIN_CODE}
      - DB_HOST=db
      - DB_NAME=lenscraft
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lenscraft-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: lenscraft-db
    environment:
      - POSTGRES_DB=lenscraft
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-srjmgr@786}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lenscraft-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d lenscraft" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:


networks:
  lenscraft-network:
    driver: bridge
